### ISSUE TITLE
[Feature] Option to hide interaction CTAs

### ISSUE THREAD

**Issue by pointydev** [raingart/Nova-YouTube-extension#125]
Would love an option to hide the call to action for the like button that can be triggered by creators. This can be achieved by applying the following basic CSS:
```css
segmented-like-dislike-button-view-model .smartimation__border,
segmented-like-dislike-button-view-model .smartimation__background {
    display: none;
}
```

See it in action here: https://youtu.be/obX2WdINsZo

Thanks,
Elliott

**Comment by raingart** [comment]
No problem. I've never seen this kind of functionality before
I will add "Clear pages of junk" to the plugin

Thanks for sharing

**Comment by pointydev** [comment]
With further research, it also appears there is [one for subscriptions too](https://youtu.be/AaA_4IvajwQ?si=qedTvb7tndFDo7w7):
```css
ytd-subscribe-button-renderer .smartimation__border,
ytd-subscribe-button-renderer .smartimation__background {
    display: none;
}
```
