### ISSUE TITLE
[Bug] "Unshort Video" + "Pin Player while Scrolling": Floating Player is too big

### ISSUE THREAD

**Issue by muescha** [raingart/Nova-YouTube-extension#188]
### Setup:
- enabled "Unshort Video" ( `shorts-redirect`)
- enabled ""Pin Player while Scrolling" ( `player-pin-scroll` )

### What I see:
- I scroll the page
- the floating player is much more bigger (see Screenshots below)

### What I expect:
- player same size as with normal video

### Possible solution:
- detect if it is a Unshorted Video (I can not see a difference in the url if it is an unshorted video)
- and adjust the scale
- if it is on normal video: `1.2` then the unshorted should have something between `2.1` and `2.2` - so I guess it is factor 1.2 x 1.8 = 2.16 (I manually can only set `2.1` or `2.2` in the settings dialog

### Debug Info:
- analysed floating `video` div in developer tools

- Player Size: `1.2`

- Normal Video:
	```css
	element.style {
	    width: 800px;
	    height: 450px;
	    left: 0px;
	    top: 0px;
	}
	```

- Unshorted Video:
	- with: `1.2`:
	```css
	    width: 754px;
	    height: 1341px;
	    left: 815px;
	    top: 0px;
	}
	```
	- with `2.1`:
	```css
	element.style {
	    width: 258px;
	    height: 459px;
	    left: 278px;
	    top: 0px;
	}
	```
	- with `2.2`:
	```css
	element.style {
	    width: 246px;
	    height: 438px;
	    left: 266px;
	    top: 0px;
	}
	```

### Example URL
- https://www.youtube.com/watch?v=T93jU7tqT04&t=15s

### Setup:
 - Browser: Chrome 127.0.6533.99
 - Tampermonkey 5.1.1
 - Nova 1.50.1b

### Screenshots

- floating player is too big
![Bildschirmfoto 2024-08-10 um 16 14 51](https://github.com/user-attachments/assets/9aebbd68-e0be-4871-8054-47b0e31e15bb)

- without scrolling (no floating player is activated)
![Bildschirmfoto 2024-08-10 um 16 14 19](https://github.com/user-attachments/assets/f8b12305-88a4-41f6-bf11-c4b9644e8970)
